[book]
authors = ["Siva Naik"]
language = "en"
multilingual = false
src = "src"
title = "Rust Notes"


[output.html]
git-repository-url = "https://github.com/sivanaikk/rust"
edit-url-template = "https://github.com/sivanaikk/rust/edit/main/{path}"

[output.html.playground]
editable = false  
runnable = false
